### ISSUE TITLE
Mouvement des agents

### ISSUE THREAD

**Issue by LuanaMarrocco-zz** [agrignard/BlockCar#2]
The version of the code in the UserMovement branch doesn't work because of a null pointer exception.

The goal of this version is to give as attribute to each User a living and a working place.

In the template line 25, I try to recover all the buildng created in the Volpe Model (I have tried different solutions but here, I have added a function in the Volpe Model, getBuilding() who returns all the building, line 229).

It seems that this function is not correct and doesn't return what I ask and I don't understand why. 

Can you hep me?

**Comment by agrignard** [comment]
I don't see wy you need to rewrite getBuildings? why don't you just do wolrd.buildings?

also in your getBuildings why do you only get the "O" buildings?

**Comment by agrignard** [comment]
ok I see the problem, the init of the template is call before the init of the main so the building are not created yet that's waht produce the NPE

This is the default behavior of GAMA, a simple way to fix this is to wait that the main init is done and then create the Block Car (for example in a global reflex of the template model which is call when cycle>1. 
 I wil see if there is a more "elegant solution"
A better way (I will ask a reuqest on that on GAMA is to be able to

**Comment by LuanaMarrocco-zz** [comment]
I have tried first only by using world.buildings and the same error occured. I thus believed that I did something wrong. Then I have tried the getBuilding (in order to have all the buildings), and it didn't work so I believed that maybe I needed to put the "where (each. ...)" statement in line 230. So I added it and no still the same problem.

Hooooo I didn't think about that !! I will check it ! Thanks

**Comment by agrignard** [comment]
you see it was not your fault ;-)
https://groups.google.com/forum/#!topic/gama-platform/67S3jYXbbo8

It's a bit conter intuitive the the init of model2 is called before model1

I just post an issue here
https://github.com/gama-platform/gama/issues/2511

**Comment by agrignard** [comment]
Ok on a  trouvé un truc plus clean.

J'ai rajouté un customInit vide dans le main et y'a juste a overider customInit dans le template.

j'ai fais la modif dans le dernier commit (le coup du cycle>1 marchait aussi mais la c'est plus clean)

Merci Alexis et Nghi ;-)
https://github.com/gama-platform/gama/issues/2511
